import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./scss/root.scss";
import "./scss/globals.css";
import "./scss/layout.scss";
import BaseHeaer, { BaseHeader } from "@/components/layout/base-header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="app">
          <BaseHeader />
          <div class="main">
          {children}
          </div>
    
       </div>
      </body>
    </html>
  );
}
